Repository sofianeK9/exo-ci-cd, pull requests merged in 2024-12, with the labels that each got.

#10 feat: add new component textfield
  src/App.jsx
  src/components/form/TextField.jsx
Labels: enhancement2, feature

#11 initialize components at app.jsx
  src/App.jsx
Labels: feature

#13 feat: creation composant paragraphe
  package-lock.json
  package.json
  src/components/typography/Paragraph.jsx
Labels: enhancement2

#14 feat: link feature create
  src/components/typography/LInk.jsx
  src/components/typography/typo.jsx
Labels: enhancement2

#15 feat: create list/feature
  src/components/typography/List.jsx
Labels: enhancement2

#12 feat: add new component textarea
  src/App.jsx
  src/components/form/TextArea.jsx
Labels: enhancement2, feature
